my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path("", views.index, name='index'),
    path("user/", include("users.urls", namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_site/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = "users"

urlpatterns = [
    # url-адреса входа и выхода
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # url-адреса смены пароля
    path(
        "password-change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # url-адреса сброса пароля
    path(
        "password-reset/", views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("register/", views.register, name="register"),
    path("profile/", views.ProfileUser.as_view(), name="profile"),
    path("add-city/", views.AddCityView.as_view(), name="add_city"),
    path("add-city/done/", views.AddCityDoneView.as_view(), name="add_city_done"),
    path("delete-user/", views.DeleteUserView, name="delete_user"),
    path("list-of-users/", views.ListUserView.as_view(), name="list_of_users"),
    path("user/<slug:username>/", views.ShowUser.as_view(), name="show_user"),
]

my_site/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.deconstruct import deconstructible
from django.core.exceptions import ValidationError
from datetime import date
from django.urls import reverse


# Create your models here.
class City(models.Model):
    name = models.CharField(
        max_length=25, unique=True, db_index=True, verbose_name="Название"
    )

    is_available = models.BooleanField(default=False, verbose_name="Доступен для выбора")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = "cities"


def user_directory_path(instance, filename):
    return "users/user_{0}/{1}".format(instance.id, filename)


@deconstructible
class TodayDateValidator:
    code = "today_date"

    def __init__(self, message=None):
        self.message = message if message else "Дата рождения не может быть в будущем"

    def __call__(self, value, *args, **kwds):
        data = str(value).split("-")
        today = str(date.today()).split("-")

        if not all(((int(data[i]) <= int(today[i])) for i in range(3))):
            raise ValidationError(self.message, code=self.code)


class User(AbstractUser):
    GENDERS = (("m", "Мужчина"), ("f", "Женщина"))

    email = models.EmailField(
        verbose_name='e-mail', blank=False, unique=True
    )

    patronymic = models.CharField(
        verbose_name="Отчество", blank=True, null=True, max_length=50, default=""
    )
    date_of_birth = models.DateField(
        verbose_name="Дата рождения",
        blank=True,
        null=True,
        validators=[
            TodayDateValidator(),
        ],
    )
    city = models.ForeignKey(to=City, null=True, on_delete=models.SET_NULL, blank=True)
    gender = models.CharField(
        verbose_name="Пол",
        max_length=1,
        blank=True,
        null=True,
        choices=GENDERS,
        default="",
    )
    image = models.ImageField(
        upload_to=user_directory_path, verbose_name="Фотография", blank=True, null=True
    )
    is_displayed = models.BooleanField(verbose_name="Отображается в списке", default=False)

    def get_absolute_url(self):
        return reverse('users:show_user', kwargs={'username': self.username})
    

my_site/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from .models import City


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingInput",
                "type": "username",
                "placeholder": "Username",
                "name": "username",
            }
        ),
    )

    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "Password",
            }
        ),
    )

    class Meta:
        model = get_user_model()
        fields = ["username", "password"]


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(
        error_messages={"unique": "Пользователь с таким логином уже существует"},
        label="Логин",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingInput",
                "type": "username",
                "placeholder": "Username",
                "name": "username",
            }
        ),
    )

    email = forms.CharField(
        label="email",
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "id": "floatingEmail",
                "type": "email",
                "placeholder": "Email",
            }
        ),
    )

    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "Password",
            }
        ),
    )

    password2 = forms.CharField(
        label="Повторите пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "Repeat password",
            }
        ),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "password",
            "password2",
        ]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Пароли не совпадают", code='password_mismatch')
        return cd["password2"]

    def clean_email(self):
        data = self.cleaned_data["email"]
        if get_user_model().objects.filter(email=data).exists():
            raise forms.ValidationError("Такой e-mail уже используется", code='unique')
        return data


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(
        error_messages={'unique': 'Пользователь с таким логином уже существует'},
        label="Логин",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingInput",
                "type": "username",
                "placeholder": "Username",
                "name": "username",
            }
        ),
    )

    email = forms.CharField(
        error_messages={'unique': 'Пользователь с таким e-mail уже существует'},
        label="E-mail",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingEmail",
                "type": "email",
                "placeholder": "Email",
            }
        ),
    )

    class CustomSelect(forms.Select):
        option_inherits_attrs = True

    gender = forms.ChoiceField(
        label='Пол',
        choices=(("", "Не указан"), ("m", "Мужчина"), ("f", "Женщина")),
        required=False,
        widget=CustomSelect(
            attrs={
                "class": "form-control text-center",
                "id": "inputState",
            }
        ),
    )

    last_name = forms.CharField(
        label="Фамилия",
        required=False,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Фамилия",
            }
        ),
    )

    first_name = forms.CharField(
        label="Имя",
        required=False,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Имя",
            }
        ),
    )

    patronymic = forms.CharField(
        label="Отчество",
        required=False,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Отчество",
            }
        ),
    )

    city = forms.ModelChoiceField(
        label='Город',
        queryset=City.objects.filter(is_available=True).order_by("name"),
        required=False,
        widget=CustomSelect(
            attrs={
                "class": "form-control text-center",
                "id": "inputState",
            }
        ),
    )

    date_of_birth = forms.DateField(
        label="Дата рождения",
        required=False,
        widget=forms.DateInput(
            format="%Y-%m-%d",
            attrs={
                "type": "date",
                "class": "form-control",
            },
        ),
        input_formats=["%Y-%m-%d"],
    )

    image = forms.FileField(
        label="image",
        required=False,
        widget=forms.FileInput(
            attrs={
                "type": "file",
                "id": "photoInput",
                "accept": "image/*",
                "class": "file-upload",
            }
        ),
    )

    is_displayed = forms.BooleanField(
        label="Отображать пользователя в списке пользователей",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "form-check-input",
                "role": "switch",
                "id": "flexSwitchCheckDefault",
            }
        ),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "patronymic",
            "gender",
            "city",
            "date_of_birth",
            "image",
            "is_displayed",
        ]


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старый пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "Old password",
            }
        ),
    )

    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "new password",
            }
        ),
    )

    new_password2 = forms.CharField(
        label="Повторите новый пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "repeat password",
            }
        ),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "old_password",
            "new_password1",
            "new_password2",
        ]


class AddCityForm(forms.ModelForm):
    name = forms.CharField(
        label="Название города",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingInput",
                "type": "text",
                "placeholder": "city_name",
                "name": "city_name",
            }
        ),
    )

    class Meta:
        model = City
        fields = [
            "name",
        ]


class DeleteUserForm(forms.Form):
    confirmation = forms.CharField(
        label="Подтверждение",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingInput",
                "type": "text",
                "placeholder": "confirmation",
                "name": "confirmation",
            }
        ),
    )

    def clean_confirmation(self):
        confirmation = self.cleaned_data["confirmation"]
        hidden_data = self.data["hidden_data"]
        if not (confirmation == f"users/{hidden_data}"):
            raise forms.ValidationError(message="Введите правильный код подтверждения")


class PasswordResetForm(PasswordResetForm):
    email = forms.CharField(
        label="E-mail",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "floatingEmail",
                "type": "email",
                "placeholder": "Email",
            }
        ),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "email",
        ]


class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="новый пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "floatingPassword",
                "type": "password",
                "placeholder": "new password",
            }
        ),
    )

    new_password2 = forms.CharField(
        label="повторите новый пароль",
        widget=forms.PasswordInput(
            attrs={

my_site/users/templates/users/add_city_done.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Город добавлен
{% endblock %}


{% block content %}
  <div class="container">
        <h1>
            Город добавлен
        </h1>
        <span>
            Вы сможете выбрать добавленный город после одобрения админом
        </span>
        <br>
        <a href="{% url 'users:profile' %}">Вернуться в профиль</a>
  </div>
{% endblock %}

my_site/users/templates/users/delete_user_done.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Пользователь удален
{% endblock %}


{% block content %}
  <div class="container">
        <h1>
            Пользователь удален
        </h1>
        <span>Вы можете</span>
        <a href="{% url 'users:register' %}">зарегистрироваться</a>
  </div>
{% endblock %}

my_site/users/templates/users/detail_user.html
{% extends "form_base.html" %}
{% load static %}


{% block title%}
  Профиль пользователя @{{ detail_user.username }}
{% endblock %}

{% block head %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style type="text/css">

    .logoimg{
      text-align: center;
    }
    .avatar-wrapper {
        position: relative;
        height: 200px;
        width: 200px;
        /*margin: 20px auto;*/
        margin: -100px auto 20px auto;
        border-radius: 50%;
        overflow: hidden;
        /*box-shadow: 1px 1px 15px -5px black;*/
        box-shadow: none;
        transition: all .3s ease;
    }

        .avatar-wrapper:hover {
            transform: scale(1.05);
            cursor: pointer;
        }

            .avatar-wrapper:hover .profile-pic {
                opacity: .5;
            }

        .avatar-wrapper .profile-pic {
            height: 100%;
            width: 100%;
            transition: all .3s ease;
        }

            .avatar-wrapper .profile-pic:after {
                font-family: FontAwesome;
                content: "\f007";
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                position: absolute;
                font-size: 190px;
                background: #ecf0f1;
                color: #34495e;
                text-align: center;
            }

        .avatar-wrapper .upload-button {
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
        }

            .avatar-wrapper .upload-button .fa-arrow-circle-up {
                position: absolute;
                font-size: 243px;
                top: -16px;
                left: -5px;
                text-align: center;
                opacity: 0;
                transition: all .3s ease;
                color: #e4eae7;
            }

            .avatar-wrapper .upload-button:hover .fa-arrow-circle-up {
                opacity: .9;
            }

    #avatar-header
    {
        /* width: 200px; */
        text-align: center;
        margin-left: 0px auto;
        margin-left: 35%;
        margin-right: 35%;
        border-radius: 30px;
    }

    .avatar-header {      
        padding-top: 10px;
        padding-bottom: 10px;
    }

    .nametitle {
        color: #fff !important;
    }

        .nametitle h3 {
            font-weight: 700 !important;
        }

    .avatar-tab li {
        width: 50%;
    }

        .avatar-tab li i {
            margin-bottom: 0px !important;
        }
    .socialtitle.text-center a img {
        width: 20px;
        cursor: pointer;
        padding: 0px 10px;
    }
    .socialtitle.text-center a i
    {
      color:#fff;
      padding: 0px 10px;
    }
    .socialtitle.text-center a i:hover
    {
      color:#000;
    }
  </style>
{% endblock %}

{% block header%}
    <header class="p-3 text-bg-dark">
        <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            {% include '../nav_temp/nav_auth.html' %}
        </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container min-vh-100 d-flex justify-content-center">
    <main class="form-signin w-50 m-auto">
      <form method="post" enctype="multipart/form-data">
        <h1 class="h1 mb-3 fw-normal" style="padding-bottom: 15px;">Профиль пользователя @{{ detail_user.username }}</h1>
        <div id="avatar-header">
              <img src="{% if detail_user.image %} ../../../media/{{ detail_user.image }} {% else %} {% static 'users/images/person-circle.svg' %} {% endif %}" alt="user_ava" width="150" height="150" class="rounded-circle">
        </div>
        <br>
        <div class="input-group mb-3">
          <span class="input-group-text">@</span>
          <div class="form-floating">
            <input type="username" name="username" value="{{ detail_user.username }}" class="form-control" id="floatingInput" placeholder="Username" required="" readonly>
            <label for="floatingInput">Логин</label>
          </div>
        </div>
        <div class="form-floating">
          <input type="email" name="email" value="{{ detail_user.email }}" class="form-control" id="floatingEmail" placeholder="Email" required="" readonly>
          <label for="floatingEmail">E-mail</label>
        </div>

        <div class="row" ,="" style="padding-top: 10px;">
          <div class="col">
            <div class="form-floating">
              <input type="text" name="last_name" value="{{ detail_user.last_name }}" class="form-control" placeholder="Фамилия" id="id_last_name" readonly>
              <label for="id_last_name">last name</label>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              <input type="text" name="first_name" value="{{ detail_user.first_name }}" class="form-control" placeholder="Имя" id="id_first_name" readonly>
              <label for="id_first_name">first name</label>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              <input type="text" name="patronymic" class="form-control" value="{{ detail_user.patronymic }}" placeholder="Отчество" id="id_patronymic" readonly>
              <label for="id_patronymic">patronymic</label>
            </div>
          </div>
        </div>

        <div class="row" ,="" style="padding-top: 10px;">
          <div class="col">
            <div class="form-group col-md-6, style=" width:="" 100px;>
              <div class="form-floating">
                <input type="text" value="{{ user_gender }}" name="gender" class="form-control text-center" id="inputState" readonly>
                <label for="inputState">Gender</label>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              <input type="text" name="city" value="{% if detail_user.city %}  {{ detail_user.city }} {% else %} {% endif %}" class="form-control text-center" id="inputState" readonly>
              <label for="inputState">City</label>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              <input type="text" name="date_of_birth" value="{% if detail_user.date_of_birth %}  {{ detail_user.date_of_birth }} {% else %} {% endif %}" class="form-control" id="id_date_of_birth" readonly>
              <label for="id_date_of_birth">Date of Birth</label>
            </div>
          </div>
        </div>

        <p style="padding-top: 10px;">© 2024 Москва</p>
      </form>
    </main>
  </div>
{% endblock %}

{% block script%}
  <script>
    /***AVATAR SCRIPT***/

    function readURL(input)
    {
        if(input.files && input.files[0]){
            var reader = new FileReader();
            reader.onload=function(e)
              {
                  var fileurl = e.target.result;
                  $('.profile-pic').attr('src', fileurl);
              }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $(".file-upload").on('change', function(){
    readURL(this);
    });
    $(".upload-button").on('click', function(){
    $(".file-upload").click();
    });
    /***AVATAR SCRIPT***/
  </script>
{% endblock %}

my_site/users/templates/users/list_of_users.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
    <div class="container">
        {% include 'users/one_user.html' %}
    </div>
{% endblock %}

my_site/users/templates/users/profile.html
{% extends "form_base.html" %}
{% load static %}


{% block title%}
  Профиль пользователя
{% endblock %}

{% block head %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style type="text/css">

    .logoimg{
      text-align: center;
    }
    .avatar-wrapper {
        position: relative;
        height: 200px;
        width: 200px;
        /*margin: 20px auto;*/
        margin: -100px auto 20px auto;
        border-radius: 50%;
        overflow: hidden;
        /*box-shadow: 1px 1px 15px -5px black;*/
        box-shadow: none;
        transition: all .3s ease;
    }

        .avatar-wrapper:hover {
            transform: scale(1.05);
            cursor: pointer;
        }

            .avatar-wrapper:hover .profile-pic {
                opacity: .5;
            }

        .avatar-wrapper .profile-pic {
            height: 100%;
            width: 100%;
            transition: all .3s ease;
        }

            .avatar-wrapper .profile-pic:after {
                font-family: FontAwesome;
                content: "\f007";
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                position: absolute;
                font-size: 190px;
                background: #ecf0f1;
                color: #34495e;
                text-align: center;
            }

        .avatar-wrapper .upload-button {
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
        }

            .avatar-wrapper .upload-button .fa-arrow-circle-up {
                position: absolute;
                font-size: 243px;
                top: -16px;
                left: -5px;
                text-align: center;
                opacity: 0;
                transition: all .3s ease;
                color: #e4eae7;
            }

            .avatar-wrapper .upload-button:hover .fa-arrow-circle-up {
                opacity: .9;
            }

    #avatar-header
    {
        /* width: 200px; */
        text-align: center;
        margin-left: 0px auto;
        margin-left: 35%;
        margin-right: 35%;
        border-radius: 30px;
        margin-top: 15%;
    }
    .avatar-header {      
        padding-top: 10px;
        padding-bottom: 10px;
        border-radius: 4px;
        margin-bottom: 20px;
    }

    .nametitle {
        color: #fff !important;
    }

        .nametitle h3 {
            font-weight: 700 !important;
        }

    .avatar-tab li {
        width: 50%;
    }

        .avatar-tab li i {
            margin-bottom: 0px !important;
        }
    .socialtitle.text-center a img {
        width: 20px;
        cursor: pointer;
        padding: 0px 10px;
    }
    .socialtitle.text-center a i
    {
      color:#fff;
      padding: 0px 10px;
    }
    .socialtitle.text-center a i:hover
    {
      color:#000;
    }
  </style>
{% endblock %}

{% block header%}
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        {% include '../nav_temp/nav_auth.html' %}
      </div>
    </div>
</header>
{% endblock %}

{% block main %}
<div class="container min-vh-100 d-flex justify-content-center">
    <main class="form-signin w-50 m-auto">
      <form method="post" enctype="multipart/form-data">
        <h1 class="h1 mb-3 fw-normal" style="padding-bottom: 15px;">Твой профиль</h1>

        <div id="avatar-header">
            <div class="avatar-wrapper">
                {% if user_photo %}
                  <img src="{{ user_photo }}" alt="ava" class="profile-pic">
                {% else %}
                  <img src="{% static 'users/images/person-circle.svg' %}" alt="ava" class="profile-pic">
                {% endif %}
                <div class="upload-button">
                    <i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
                </div>
                {{ form.image }}
            </div>
            <input type="checkbox" name="checkbox" class="btn-check" id="btn-check-2-outlined" autocomplete="off">
            <label class="btn btn-outline-secondary" for="btn-check-2-outlined">Фотография по умолчанию</label>
        </div>
        <br>
        <div class="input-group mb-3">
          <span class="input-group-text">@</span>
          <div class="form-floating">
            {{ form.username }}
            <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
          </div>
        </div>
        {% if form.username.errors %}
        <div style="font-size:100%;color:#e90000">
          {{ form.username.errors }}
        </div>
        {% endif %}
        <div class="form-floating">
          {{ form.email }}
          <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
        </div>
        {% if form.email.errors %}
        <div style="font-size:100%;color:#e90000">
          {{ form.email.errors }}
        </div>
        {% endif %}

        <div class="row", style="padding-top: 10px;">
          <div class="col">
            <div class="form-floating">
              {{ form.last_name }}
              <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              {{ form.first_name }}
              <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              {{ form.patronymic }}
              <label for="{{ form.patronymic.id_for_label }}">{{ form.patronymic.label }}</label>
            </div>
          </div>
        </div>

        <div class="row", style="padding-top: 10px;">
          <div class="col">
            <div class="form-group col-md-6, style="width: 100px;">
              <div class="form-floating">
                {{ form.gender }}
                <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}</label>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              {{ form.city }}
              <label for="{{ form.city.id_for_label }}">{{ form.city.label }}</label>
            </div>
          </div>
          <div class="col">
            <div class="form-floating">
              {{ form.date_of_birth }}
              <label for="{{ form.date_of_birth.id_for_label }}">{{ form.date_of_birth.label }}</label>
            </div>
            {% if form.date_of_birth.errors %}
              <div style="font-size:100%;color:#e90000">
                {{ form.date_of_birth.errors }}
              </div>
            {% endif %}
          </div>
        </div>

        <div style="padding-top: 10px; padding-left: 10px">
          <div class="form-check form-switch">
            {{ form.is_displayed }}
            <label class="form-check-label" for="flexSwitchCheckDefault">{{ form.is_displayed.label }}</label>
          </div>
        </div>

        <div class="row" style="padding: 10px;">
          <div class="col text-center">
            <a href="{% url 'users:password_change' %}" style="color: #68e5e9; text-decoration: none;">Изменить пароль</a>
          </div>
          <div class="col text-center">
            <a href="{% url 'users:add_city' %}" style="color: #eb0dff; text-decoration: none;">Добавить свой город</a>
          </div>
          <div class="col text-center">
            <a href="{% url 'users:delete_user' %}" style="color: #e90000; text-decoration: none;">Удалить аккаунт</a>
          </div>
        </div>

        <button class="btn btn-primary w-100 py-2" type="submit">Обновить данные</button>
        <p style="padding-top: 10px;">© 2024 Москва</p>
        {% csrf_token %}
      </form>
    </main>
  </div>
{% endblock %}

{% block script%}
  <script>
    /***AVATAR SCRIPT***/

    function readURL(input)
    {
        if(input.files && input.files[0]){
            var reader = new FileReader();
            reader.onload=function(e)
              {
                  var fileurl = e.target.result;
                  $('.profile-pic').attr('src', fileurl);
              }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $(".file-upload").on('change', function(){
    readURL(this);
    });
    $(".upload-button").on('click', function(){
    $(".file-upload").click();
    });
    /***AVATAR SCRIPT***/
  </script>
{% endblock %}